server:
  port: 8081
#  servlet:
#    context-path: /bears

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    username: root
    password: Subhana@2020
    url: jdbc:mysql://34.130.13.72:3306/TeleMedeAPP
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true